### ISSUE TITLE
Getting java.util.ConcurrentModificationException error

### ISSUE THREAD

**Issue by pradeepbbl** [ogibayashi/kafka-topic-exporter#1]
Hi,

We are continuously ConcurrentModificationException

2017-08-08 13:48:09,610 [qtp87765719-47 - /metrics] (org.eclipse.jetty.servlet.ServletHandler:513) WARN  /metrics
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollector.collect(KafkaCollector.java:70)
	at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollector.collect(KafkaCollector.java:61)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:72)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:64)
	at io.prometheus.client.CollectorRegistry.metricFamilySamples(CollectorRegistry.java:55)
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:41)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)

Thanks,

**Comment by ogibayashi** [comment]
Thank you for your report! 
Fixed by #2
