### ISSUE TITLE
Build fails with latest code

### ISSUE THREAD

**Issue by aarthipa** [ogibayashi/kafka-topic-exporter#12]
~/git/kafka-topic-exporter$ git branch
* master

/git/kafka-topic-exporter$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building kafka-topic-exporter 0.0.6
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-topic-exporter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ kafka-topic-exporter ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-topic-exporter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/aparasur/git/kafka-topic-exporter/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ kafka-topic-exporter ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ kafka-topic-exporter ---
[INFO] Surefire report directory: /home/aparasur/git/kafka-topic-exporter/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.703 sec <<< FAILURE! - in jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest
testReplaceValueWithSameLabel(jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem:
        The method getLabels() is undefined for the type KafkaExporterLogEntry
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest.testReplaceValueWithSameLabel(KafkaCollectorTest.java:90)

testMetricExpire(jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem:
        The method getLabels() is undefined for the type KafkaExporterLogEntry
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest.testMetricExpire(KafkaCollectorTest.java:117)

testAddSimpleMetric(jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem:
        The method getName() is undefined for the type KafkaExporterLogEntry
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollector.add(KafkaCollector.java:40)
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollector.add(KafkaCollector.java:33)
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest.testAddSimpleMetric(KafkaCollectorTest.java:25)

testAddMetricWithLabelAndTimestamp(jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem:
        The method getLabels() is undefined for the type KafkaExporterLogEntry
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest.testAddMetricWithLabelAndTimestamp(KafkaCollectorTest.java:67)

testAddMetricWithLabel(jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problem:
        The method getLabels() is undefined for the type KafkaExporterLogEntry
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest.testAddMetricWithLabel(KafkaCollectorTest.java:49)

Running jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec <<< FAILURE! - in jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest
testHashCode(jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest)  Time elapsed: 0 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<982007015> but was:<1232306490>
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.failNotEquals(Assert.java:282)
        at junit.framework.Assert.assertEquals(Assert.java:64)
        at junit.framework.Assert.assertEquals(Assert.java:201)
        at junit.framework.Assert.assertEquals(Assert.java:207)
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest.testHashCode(KafkaExporterLogEntryTest.java:29)

testEquals(jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest)  Time elapsed: 0 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntry@79be0360> but was:<jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntry@22a67b4>
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.failNotEquals(Assert.java:282)
        at junit.framework.Assert.assertEquals(Assert.java:64)
        at junit.framework.Assert.assertEquals(Assert.java:71)
        at jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest.testEquals(KafkaExporterLogEntryTest.java:20)

Results :

Failed tests:
  jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest#testHashCode AssertionFailedError
  jp.gr.java_conf.ogibayashi.prometheus.KafkaExporterLogEntryTest#testEquals AssertionFailedError

Tests in error:
  jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest#testReplaceValueWithSameLabel Error
  jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest#testMetricExpire Error
  jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest#testAddSimpleMetric Error
  jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest#testAddMetricWithLabelAndTimestamp Error
  jp.gr.java_conf.ogibayashi.prometheus.KafkaCollectorTest#testAddMetricWithLabel Error

Tests run: 7, Failures: 2, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.603 s
[INFO] Finished at: 2018-08-01T10:04:40+00:00
[INFO] Final Memory: 13M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project kafka-topic-exporter: There are test failures.
[ERROR]
[ERROR] Please refer to /home/xxx/git/kafka-topic-exporter/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ogibayashi** [comment]
Hmm.. I tried cloning repository and then `mvn install`, it worked.
Which version of java are you using?

**Comment by ddvogt** [comment]
It's late, but for the record: set your java version correctly, e.g. `export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home` before running `mvn install`
